# TODO: license

FROM geopython/pygeoapi:latest

RUN apt update \
    && apt install --no-install-recommends -y \
        git \
        build-essential \
        # for ogc-edc dependencies
        python3-pip libxml2 libxml2-dev libxslt-dev python3-dev \
        # for eoxserver
        libpq-dev \
    && rm -rf /var/lib/apt/lists/

RUN pip install git+git://github.com/EOxServer/eoxserver.git

RUN git clone https://github.com/eurodatacube/ogc-edc.git \
    && cd ogc-edc \
    # set fixed commit, otherwise docker will cache anything
    && git checkout 5f2844e5dbf63f05d8076965b02171bd91871820 \
    && pip3 install -r requirements.txt
ENV PYTHONPATH="/pygeoapi/ogc-edc"

ADD dispatch_app.py /pygeoapi
RUN sed -i s'/pygeoapi.flask_app:APP/dispatch_app:app/' /entrypoint.sh

ADD local.config.yml /pygeoapi/local.config.yml
