# TODO: license

FROM geopython/pygeoapi:latest

RUN apt update && apt install -y python3-pip git

RUN git clone https://github.com/eurodatacube/ogc-edc.git
RUN apt install -y libxml2 libxml2-dev libxslt-dev python3-dev libxml2-dev libxslt-dev
RUN cd ogc-edc && pip3 install -r requirements.txt
ENV PYTHONPATH="/pygeoapi/ogc-edc"

RUN apt install libpq-dev
RUN pip install git+git://github.com/EOxServer/eoxserver.git

ADD dispatch_app.py /pygeoapi


RUN sed -i s'/pygeoapi.flask_app:APP/dispatch_app:app/' /entrypoint.sh
